### ISSUE TITLE
System Sequence Diagrams

### ISSUE THREAD

**Issue by GermanBeast7** [blueappleee/EmployeeManagementSystem#5]
With Activity Diagrams create the system sequence diagrams

**Comment by jasonxiexy** [comment]
![sequence_diagram_assignLevel drawio](https://user-images.githubusercontent.com/60050513/201736533-b357690f-0d9d-4017-a29e-e2913a640935.png)
![sequence_diagram_assignTeam drawio](https://user-images.githubusercontent.com/60050513/201736535-435224ec-86e2-41e7-bb57-a11266b7b685.png)

According to the two selected detailed use case, here are the corresponding sequence diagrams.
